version: '3.9'

services:
  db:
    container_name: pg_db
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: my_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
  test_db:
    container_name: test_pg_db
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5433:5432"
    volumes:
      - test_postgres_data:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

  public_api:
    build:
      context: ./public_api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - ./db:/app/db
    
  private_api:
    build:
      context: ./private_api
      dockerfile: Dockerfile
    ports:
      - "8001:8000"
    environment:
      - MINIO_BUCKET_NAME=memes
      - AUTH_TOKEN=JflNaq4Pmsh8fhJq
    depends_on:
      - db
      - minio
    volumes:
      - ./db:/app/db
      - ./s3:/app/s3

  minio:
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: madsoft_admin
      MINIO_ROOT_PASSWORD: madsoft_password
    volumes:
      - minio_data:/data
      - ./init_minio.sh:/usr/bin/init_minio.sh
    entrypoint: /usr/bin/init_minio.sh

  tests:
    build:
      context: ./tests
      dockerfile: Dockerfile
    depends_on:
      - public_api
      - private_api
      - test_db
    environment:
      AUTH_TOKEN: JflNaq4Pmsh8fhJq
    volumes:
      - ./db:/db
      - ./s3:/s3
      - ./public_api:/public_api
      - ./public_api/app/routes:/routes
      - ./private_api:/private_api
      - ./private_api/app/private_routes:/private_routes


volumes:
  minio_data:
  test_postgres_data:
  postgres_data:
